Identifier: local.munki.pkg-config
Input:
  MUNKI_REPO_SUBDIR: apps/pkg-config
  NAME: pkg-config
  pkginfo:
    catalogs:
    - testing
    category: Development
    description: pkg-config is a helper tool used when compiling applications and
      libraries.
    developer: GNOME
    display_name: '%NAME%'
    name: '%NAME%'
    unattended_install: true
ParentRecipe: com.github.humanendpoint.munki.pkg-config
ParentRecipeTrustInfo:
  non_core_processors:
    com.github.humanendpoint.processors/BuildMaker:
      git_hash: 5cb2b8a3ea42329fb93961fb541ebb221b174108
      path: ~/work/munki/munki/autopkg/recipes/processors/BuildMaker.py
      sha256_hash: f73b95fa7ce7b0c9bc007ce0670bc33b7acfb1501d2545f6435d9f3dede61c3c
    com.github.humanendpoint.processors/URLDownloaderPython:
      git_hash: 5cb2b8a3ea42329fb93961fb541ebb221b174108
      path: ~/work/munki/munki/autopkg/recipes/processors/URLDownloaderPython.py
      sha256_hash: 72337e153221fe1ba908684482f220ad376e59ad3b3a8f37b4bd0b7268998296
    com.github.humanendpoint.processors/URLVersionSearcher:
      git_hash: 5cb2b8a3ea42329fb93961fb541ebb221b174108
      path: ~/work/munki/munki/autopkg/recipes/processors/URLVersionSearcher.py
      sha256_hash: 281b907d444f7c839f701417bdeeed942641deba1b64238bc0ba4846891eaf65
    com.github.rtrouton.SharedProcessors/PkgSigner:
      git_hash: 56fc1ee3588f12cdd86e4e202821229873c27e21
      path: ~/Library/AutoPkg/RecipeRepos/com.github.autopkg.rtrouton-recipes/SharedProcessors/PkgSigner.py
      sha256_hash: 464d1756f190a0161a6a00358cd42042bcdb5213802624d9ac58d3e723877a56
  parent_recipes:
    com.github.humanendpoint.download.pkg-config:
      git_hash: 5cb2b8a3ea42329fb93961fb541ebb221b174108
      path: ~/work/munki/munki/autopkg/recipes/pkg-config/pkg-config.download.recipe.yaml
      sha256_hash: 8754bce48041818913149e98259e962caf3d8b7356335f730703885af9babcfe
    com.github.humanendpoint.munki.pkg-config:
      git_hash: 5cb2b8a3ea42329fb93961fb541ebb221b174108
      path: ~/work/munki/munki/autopkg/recipes/pkg-config/pkg-config.munki.recipe.yaml
      sha256_hash: 1409fc5e29cc46c80ba52ad0feeb54cff60a0892f4a1246f6fbbbc2fc8a36c51
    com.github.humanendpoint.pkg.pkg-config:
      git_hash: 5cb2b8a3ea42329fb93961fb541ebb221b174108
      path: ~/work/munki/munki/autopkg/recipes/pkg-config/pkg-config.pkg.recipe.yaml
      sha256_hash: e0873473e3bfa564801ad997a45da84c12dfe504e668c645395b543f0abd504f
    com.github.humanendpoint.sign.pkg-config:
      git_hash: 5cb2b8a3ea42329fb93961fb541ebb221b174108
      path: ~/work/munki/munki/autopkg/recipes/pkg-config/pkg-config.sign.recipe.yaml
      sha256_hash: 119e3b5369d72ac2ba7d4eae63d57a202afcf34ccb8bef8293f362a2b5f19b8a
