name: Delete Manifest

on:
  workflow_dispatch:
    inputs:
      SERIAL:
        description: serial number
        required: true

env:
  SERIAL: ${{ inputs.SERIAL }}

jobs:
  manifestremoval:
    name: Manifest Removal
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Execute removal
        id: removal_step
        run: |
          if [ -e "$GITHUB_WORKSPACE/munki_repo/manifests/$SERIAL" ]; then
            PR_BRANCH="Remove-$SERIAL"
            echo "PR_BRANCH=$PR_BRANCH" >> $GITHUB_OUTPUT
            rm "$GITHUB_WORKSPACE/munki_repo/manifests/$SERIAL"
            echo "file_removed=true" >> $GITHUB_OUTPUT
          else
            echo "The file '$GITHUB_WORKSPACE/munki_repo/manifests/$SERIAL' does not exist. Skipping removal."
            echo "file_removed=false" >> $GITHUB_OUTPUT
          fi

      - name: GCS Auth
        if: steps.removal_step.outputs.file_removed == 'true'
        uses: google-github-actions/auth@v2
        with:
          token_format: 'access_token'
          credentials_json: "${{ secrets.GCP_CREDENTIALS }}"

      - name: Setup Cloud SDK
        if: steps.removal_step.outputs.file_removed == 'true'
        uses: google-github-actions/setup-gcloud@v2

      - name: Remove from bucket
        if: steps.removal_step.outputs.file_removed == 'true'
        id: upload-file
        run: gsutil rm gs://oit-munki/manifests/$SERIAL

      - name: Create Pull Request
        id: cpr
        if: steps.removal_step.outputs.file_removed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          branch: ${{ steps.removal_step.outputs.PR_BRANCH }}
          commit-message: '[skip ci] remove $SERIAL'
          title: '[skip ci] Removal of client manifest'
          body: |
            This PR is automatically generated by Github Actions, after a trigger from Okta workflows.

      - name: Send output to Slack
        if: steps.removal_step.outputs.file_removed == 'true'
        run: |
          payload='{
            "attachments": [
              {
                "blocks": [
                  {
                    "type": "section",
                    "text": {
                      "type": "mrkdwn",
                      "text": "*Manifest deleted!*\nSerial number: $SERIAL\n\nPull request opened: <${{ steps.cpr.outputs.pull-request-url }}|${{ steps.cpr.outputs.pull-request-url }}>"
                    }
                  }
                ]
              }
            ]
          }'
          echo "$payload" | curl -X POST -H 'Content-type: application/json' --data @- ${{ secrets.SLACK_WEBHOOK_OIT_PULLREQS }}
